"""CRM prompt_pack: selects the ChatBot system-prompt pack for a CRM's tenants.

Adds ``crms.prompt_pack`` (nullable — a NULL/unrecognized value falls back to
the "generic" pack at prompt-build time, see src/dialogue/packs). Backfills
every existing crms row to 'betting' so today's production behavior (the
betting/gambling SCOPE text and example phrases) is unchanged for CRMs that
were already live before this column existed — confirmed via a read-only
query against the configured DB before writing this migration (1 row,
id='betstudio', as of 2026-09-04).

Note: hand-written rather than autogenerated — this DB's autogenerate diff
picks up unrelated tables/schema drift from other applications sharing the
same database (not part of this app's Base.metadata) and is not safe to run
as-is.

Revision: 0016_crm_prompt_pack
Down: 0015_deposit_verification
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0016_crm_prompt_pack"
down_revision = "0015_deposit_verification"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column("crms", sa.Column("prompt_pack", sa.String(50), nullable=True))
    op.execute(sa.text("UPDATE crms SET prompt_pack = 'betting' WHERE prompt_pack IS NULL"))


def downgrade() -> None:
    op.drop_column("crms", "prompt_pack")
