"""CRM bundled_kb_pack: selects the bundled KB pack auto-seeded for a CRM.

Adds ``crms.bundled_kb_pack`` (nullable — NULL means this CRM gets NO bundled
docs auto-seeded at boot; an unrecognized value also seeds nothing, since it
matches no ``kb_dir``'s pack name; see ``_seed_crm_kb`` in src/main.py and
data/kb/packs/betting-default/). Backfills every existing crms row to
'betting-default' so today's production behavior (the KYC/wallet/deposits/
withdrawals/responsible-gaming bundled docs) is unchanged for CRMs that were
already live before this column existed — confirmed via a read-only query
against the configured DB before writing this migration (1 row, id='betstudio',
as of 2026-09-05, same row Task 1's 0016 migration found).

Note: hand-written rather than autogenerated — this DB's autogenerate diff
picks up unrelated tables/schema drift from other applications sharing the
same database (not part of this app's Base.metadata) and is not safe to run
as-is (same caveat as 0016_crm_prompt_pack).

Revision: 0017_crm_bundled_kb_pack
Down: 0016_crm_prompt_pack
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0017_crm_bundled_kb_pack"
down_revision = "0016_crm_prompt_pack"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column("crms", sa.Column("bundled_kb_pack", sa.String(50), nullable=True))
    op.execute(
        sa.text(
            "UPDATE crms SET bundled_kb_pack = 'betting-default' "
            "WHERE bundled_kb_pack IS NULL"
        )
    )


def downgrade() -> None:
    op.drop_column("crms", "bundled_kb_pack")
