"""CRM pronunciation_overrides: per-CRM TTS pronunciation-fix overrides.

Adds ``crms.pronunciation_overrides`` (nullable JSON — NULL/empty means this
CRM gets no extra terms beyond the generic
``src.pipeline.text_normalize.DEFAULT_PRONUNCIATIONS`` default; merged in at
TTS-synthesis time via ``normalize_for_tts(text, extra=...)``, see
``src/auth/db_resolver.py`` and ``src/bootstrap.py``). Backfills the existing
CRM's row with exactly the betting-vertical entries removed from
``DEFAULT_PRONUNCIATIONS`` in this same change, so today's production
pronunciation behavior (Casino/Aviator/Cricket/etc.) is unchanged — confirmed
via a read-only query against the configured DB before writing this migration
(1 row, id='betstudio', as of 2026-09-05, same row Task 1/2's 0016/0017
migrations found).

Note: hand-written rather than autogenerated — this DB's autogenerate diff
picks up unrelated tables/schema drift from other applications sharing the
same database (not part of this app's Base.metadata) and is not safe to run
as-is (same caveat as 0016_crm_prompt_pack / 0017_crm_bundled_kb_pack).

Revision: 0018_crm_pronunciation_overrides
Down: 0017_crm_bundled_kb_pack
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0018_crm_pronunciation_overrides"
down_revision = "0017_crm_bundled_kb_pack"
branch_labels = None
depends_on = None

# Exactly the betting-vertical entries removed from DEFAULT_PRONUNCIATIONS in
# src/pipeline/text_normalize.py by this same change (see that file's history /
# this migration's sibling commit) -- verified against the live file, not
# transcribed from memory.
_BETTING_PRONUNCIATIONS = {
    "Casino": "कसीनो",
    "Aviator": "एविएटर",
    "betting": "बेटिंग",
    "Cricket": "क्रिकेट",
    "Football": "फुटबॉल",
    "Matka": "मटका",
    "Sports": "स्पोर्ट्स",
    "Tennis": "टेनिस",
    "Basketball": "बास्केटबॉल",
    "market": "मार्केट",
    "match": "मैच",
    "matches": "मैचेस",
    "IPL": "आईपीएल",
}


def upgrade() -> None:
    op.add_column("crms", sa.Column("pronunciation_overrides", sa.JSON(), nullable=True))
    # SQLAlchemy Core (not raw text SQL) so the JSON type adapter serializes
    # the dict correctly for the driver in use, rather than relying on a
    # literal/bound-param JSON cast that varies by DB driver.
    crms = sa.table(
        "crms",
        sa.column("pronunciation_overrides", sa.JSON()),
    )
    op.execute(
        crms.update()
        .where(crms.c.pronunciation_overrides.is_(None))
        .values(pronunciation_overrides=_BETTING_PRONUNCIATIONS)
    )


def downgrade() -> None:
    op.drop_column("crms", "pronunciation_overrides")
