"""alembic/versions/0020_chat_turn_metrics.py

Two new sibling tables for ChatBot's turn-metrics pipeline (Phase 2 of
docs/superpowers/plans/2026-09-08-chatbot-turn-metrics.md) — the chat
counterpart to voice's ``turn_metrics`` (see 0011_turn_metrics.py), sized to
chat's own grain rather than an extension of that table (see the plan's §2
for why sharing would have silently corrupted
``GET /benchmarks/turn-metrics/summary``'s provider-combo grouping, which has
no ``WHERE`` clause).

``chat_turn_metrics`` — one row per completed agent turn.
``chat_tool_metrics`` — one row per tool call within a turn, FK CASCADE to
the parent (deleting a turn deletes its tool-call rows).

Both `created_at` alone and `(tenant_id, created_at)` are indexed on the
parent from day one — see 0019_turn_metrics_created_at_index.py's own
docstring for the incident (an unindexed created_at column on a
continuously-queried, growing table) this is written to avoid repeating.

Note: hand-written rather than autogenerated — this DB's autogenerate diff
picks up unrelated tables/schema drift from other applications sharing the
same database (not part of this app's Base.metadata) and is not safe to run
as-is (see 0016/0017/0018's own notes on this).

This migration must be applied manually by the project owner BEFORE
deploying the code that references these tables — a pre-migration deploy
degrades gracefully to "no rows, one WARNING per turn" rather than an outage,
since ``record_chat_turn_metric`` (src/models/chat_turn_metrics.py) swallows
every DB error, but the intended ordering is still: apply 0020, then deploy.

Revision: 0020_chat_turn_metrics
Down: 0019_turn_metrics_created_at_index
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0020_chat_turn_metrics"
down_revision = "0019_turn_metrics_created_at_index"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "chat_turn_metrics",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("tenant_id", sa.String(50), sa.ForeignKey("tenants.id", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("crm_id", sa.String(50), nullable=True),
        sa.Column("session_id", sa.String(100), nullable=False),
        sa.Column("trace_id", sa.String(100), nullable=True),
        sa.Column("path", sa.String(20), nullable=False),
        sa.Column("llm_provider", sa.String(100), nullable=False),
        sa.Column("llm_model", sa.String(100), nullable=False),
        sa.Column("action", sa.String(50), nullable=False),
        sa.Column("total_ms", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("llm_total_ms", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("llm_calls", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("tool_total_ms", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("tool_calls", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("tool_failures", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("tool_timeouts", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("tool_calls_skipped", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("kb_search_ms", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("kb_searches", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("retrieved_chunks", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("rounds", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("rounds_exhausted", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("retry_fired", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("failure_directive_fired", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("failure_directive_escalated", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("guard_hallucination_fired", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("guard_no_grounding_fired", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("guard_unverified_data_fired", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("escalated", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("idx_chat_turn_metrics_tenant", "chat_turn_metrics", ["tenant_id"])
    op.create_index("idx_chat_turn_metrics_trace_id", "chat_turn_metrics", ["trace_id"])
    op.create_index("idx_chat_turn_metrics_created_at", "chat_turn_metrics", ["created_at"])
    op.create_index(
        "idx_chat_turn_metrics_tenant_created", "chat_turn_metrics", ["tenant_id", "created_at"],
    )

    op.create_table(
        "chat_tool_metrics",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("turn_id", sa.Integer(), sa.ForeignKey("chat_turn_metrics.id", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("tenant_id", sa.String(50), nullable=False),
        sa.Column("tool_name", sa.String(100), nullable=False),
        sa.Column("kind", sa.String(30), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("outcome", sa.String(30), nullable=False),
        sa.Column("budget_slice_ms", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("round_index", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("idx_chat_tool_metrics_turn_id", "chat_tool_metrics", ["turn_id"])
    op.create_index(
        "idx_chat_tool_metrics_name_created", "chat_tool_metrics", ["tool_name", "created_at"],
    )


def downgrade() -> None:
    # Drop indexes then tables, child before parent (the child's FK points at
    # the parent).
    op.drop_index("idx_chat_tool_metrics_name_created", table_name="chat_tool_metrics")
    op.drop_index("idx_chat_tool_metrics_turn_id", table_name="chat_tool_metrics")
    op.drop_table("chat_tool_metrics")

    op.drop_index("idx_chat_turn_metrics_tenant_created", table_name="chat_turn_metrics")
    op.drop_index("idx_chat_turn_metrics_created_at", table_name="chat_turn_metrics")
    op.drop_index("idx_chat_turn_metrics_trace_id", table_name="chat_turn_metrics")
    op.drop_index("idx_chat_turn_metrics_tenant", table_name="chat_turn_metrics")
    op.drop_table("chat_turn_metrics")
