"""alembic/versions/0021_chat_turn_metrics_tokens.py

Adds three token-count columns to ``chat_turn_metrics``:
``input_tokens``, ``output_tokens``, ``cached_tokens``. These exist
specifically to answer "is prompt caching actually happening" without
requiring log-scraping (see src/models/chat_turn_metrics.py's
``ChatTurnMetric.input_tokens`` comment for the full rationale —
``cached_tokens`` should always be <= ``input_tokens`` for a healthy row,
though that is not enforced at the DB level).

Same convention as every other integer column on this table (see
0020_chat_turn_metrics.py): ``NOT NULL``, ``server_default '0'``, so
``AVG``/percentile queries over these columns never need a ``COALESCE`` and
existing rows backfill to 0 rather than NULL.

Note: hand-written rather than autogenerated — this DB's autogenerate diff
picks up unrelated tables/schema drift from other applications sharing the
same database (not part of this app's Base.metadata) and is not safe to run
as-is (see 0016/0017/0018/0020's own notes on this).

This migration must be applied manually by the project owner BEFORE
deploying the code that reads/writes these columns — a pre-migration deploy
degrades gracefully (``record_chat_turn_metric`` swallows every DB error, so
an unrecognized column on insert costs "no rows, one WARNING per turn", not
an outage), but the intended ordering is still: apply 0021, then deploy.

Revision: 0021_chat_turn_metrics_tokens
Down: 0020_chat_turn_metrics
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0021_chat_turn_metrics_tokens"
down_revision = "0020_chat_turn_metrics"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "chat_turn_metrics",
        sa.Column("input_tokens", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "chat_turn_metrics",
        sa.Column("output_tokens", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "chat_turn_metrics",
        sa.Column("cached_tokens", sa.Integer(), nullable=False, server_default="0"),
    )


def downgrade() -> None:
    # Reverse order from upgrade().
    op.drop_column("chat_turn_metrics", "cached_tokens")
    op.drop_column("chat_turn_metrics", "output_tokens")
    op.drop_column("chat_turn_metrics", "input_tokens")
